#!/usr/bin/env python3
"""score_confidence.py -- rescore every contact by how the address was obtained.

Why this exists: `email_confidence` currently mixes two unrelated things. A row
scraped off a company's own contact page and a row that `scraper.py:infer_email()`
invented as `firstname@domain` can both read 65, so the sender cannot tell a
finding from a guess. 4,839 of 7,095 live contacts are guesses; 129 are findings.

This rewrites confidence so the number means one thing only: **how strong is the
evidence that this address exists**. Provenance, not deliverability -- an SMTP
probe answers a different question and is recorded separately in
`email_verified`.

Tiers, highest evidence first:

    100  published    read off the company's own site (mailto: or page text)
     95  researched   found by hand / targeted search, one address at a time
     75  list         curated HR list, local-part shows a real naming scheme
     35  unattributed real-looking address, provenance lost
     15  guessed      firstname@domain, invented by a pattern generator

The 15 is deliberately below any sane send threshold. Those rows are not
deleted -- they name a real person at a real company, so they are worth
re-resolving against the live site. They just must not be mailed as they stand.

A `firstname@domain` shape is treated as a guess even when the source is a
curated list, because the two are indistinguishable after the fact and the
false-positive direction here costs a bounce.

Usage:
  python3 score_confidence.py              # report only, writes nothing
  python3 score_confidence.py --apply
  python3 score_confidence.py --apply --db turso-full.db
"""
import argparse
import os
import re
import shutil
import sqlite3
import sys
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_DB = os.path.join(HERE, "turso-full.db")

# Confidence awarded per provenance class.
TIERS = {
    "published": 100,
    "researched": 95,
    "list": 75,
    "unattributed": 35,
    "guessed": 15,
}

# Sources whose rows were read off the company's own website.
PUBLISHED_SOURCES = ("site_scrape",)

# Sources where a human went looking for one specific address.
RESEARCHED_SOURCES = ("manual", "manual-research", "manual-2026-dump", "SEARCHED:", "CONSTRUCTED:")

# Sources that arrived as a bought/curated contact list rather than a crawl.
LIST_SOURCES = (
    "hr_seed_", "xlsx_import", "hr_list_xlsx", "hr_lists_merge",
    "hr_contacts_merge", "yc_top2k_merge", "51-startups", "yc_import",
)

# Patterns emitted by scraper.py:infer_email(). Anything here is invented.
GUESS_PATTERNS = {"firstname", "f.lastname", "firstlast", "first.last", "flast"}

SPLIT_NAME = re.compile(r"[\s.'\-]+")


def first_name_of(name: str | None) -> str | None:
    """Lowercased first token of a person's name, or None if unusable."""
    if not name:
        return None
    parts = [p for p in SPLIT_NAME.split(name.strip()) if p]
    return parts[0].lower() if parts else None


def local_part(email: str) -> str:
    return email.split("@", 1)[0].lower()


def looks_guessed(email: str, name: str | None) -> bool:
    """True when the local-part is exactly the person's first name.

    That is the one shape `infer_email()` produces, and a real address that
    happens to match it is indistinguishable from a generated one. Treating the
    ambiguous case as a guess costs a re-resolve; treating it as real costs a
    bounce, and bounces are what get a sending domain flagged.
    """
    first = first_name_of(name)
    if not first or len(first) < 2:
        return False
    return local_part(email) == first


def starts_with_any(value: str | None, prefixes) -> bool:
    if not value:
        return False
    return any(value.startswith(p) for p in prefixes)


def classify(row) -> tuple[str, str]:
    """Return (provenance_class, one-line reason) for a contact row."""
    email = (row["email"] or "").strip()
    source = row["source"] or ""
    pattern = (row["scraped_pattern"] or "").strip().lower()
    old_conf = row["email_confidence"]
    has_url = bool(row["source_url"])

    # Strongest evidence: the company published it and we kept the URL.
    if pattern == "found" or starts_with_any(source, PUBLISHED_SOURCES):
        return "published", "read off the company's own site"
    if has_url and old_conf is not None and old_conf >= 100:
        return "published", "published address with a recorded source URL"

    # A pattern-generated address is a guess regardless of what else is true,
    # so this is checked before the source-based tiers below.
    if pattern in GUESS_PATTERNS:
        return "guessed", f"generated by pattern '{pattern}'"
    if looks_guessed(email, row["name"]):
        return "guessed", "local-part is exactly the first name"

    if starts_with_any(source, RESEARCHED_SOURCES):
        return "researched", "found by hand for this one contact"
    if old_conf is not None and 90 <= old_conf < 100:
        return "researched", "carried a hand-research confidence"

    if starts_with_any(source, LIST_SOURCES):
        return "list", "curated contact list, non-generated local-part"

    return "unattributed", "real-looking address, provenance not recorded"


def ensure_schema(con) -> list[str]:
    cols = {r["name"] for r in con.execute("PRAGMA table_info(contacts)")}
    added = []
    if "email_provenance" not in cols:
        con.execute("ALTER TABLE contacts ADD COLUMN email_provenance VARCHAR(16)")
        added.append("email_provenance")
    if "confidence_scored_at" not in cols:
        con.execute("ALTER TABLE contacts ADD COLUMN confidence_scored_at DATETIME")
        added.append("confidence_scored_at")
    return added


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--db", default=DEFAULT_DB)
    ap.add_argument("--apply", action="store_true",
                    help="write the new scores; without it nothing is changed")
    ap.add_argument("--include-invalid", action="store_true",
                    help="also rescore rows already marked is_invalid")
    args = ap.parse_args()

    if not os.path.exists(args.db):
        print(f"no such database: {args.db}", file=sys.stderr)
        return 1

    if args.apply:
        stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        backup = f"{args.db}.backup-{stamp}"
        shutil.copy2(args.db, backup)
        print(f"backup: {os.path.basename(backup)}\n")

    con = sqlite3.connect(args.db)
    con.row_factory = sqlite3.Row

    added = ensure_schema(con)
    if added:
        print(f"added columns: {', '.join(added)}\n")

    where = "" if args.include_invalid else "WHERE is_invalid = 0"
    rows = con.execute(
        f"""SELECT id, email, name, source, scraped_pattern, email_confidence,
                   source_url, email_verified
            FROM contacts {where}"""
    ).fetchall()

    counts: dict[str, int] = {}
    reasons: dict[str, str] = {}
    updates = []
    skipped_no_email = 0

    for row in rows:
        if not row["email"]:
            skipped_no_email += 1
            continue
        cls, reason = classify(row)
        counts[cls] = counts.get(cls, 0) + 1
        reasons.setdefault(cls, reason)
        updates.append((TIERS[cls], cls, row["id"]))

    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    total = len(updates)

    print(f"{'class':<14}{'conf':>6}{'count':>9}{'share':>8}  basis")
    print("-" * 78)
    for cls in ("published", "researched", "list", "unattributed", "guessed"):
        n = counts.get(cls, 0)
        if not n:
            continue
        share = f"{100 * n / total:.1f}%"
        print(f"{cls:<14}{TIERS[cls]:>6}{n:>9}{share:>8}  {reasons[cls]}")
    print("-" * 78)
    print(f"{'total':<14}{'':>6}{total:>9}")
    if skipped_no_email:
        print(f"skipped (no email): {skipped_no_email}")

    sendable = sum(counts.get(c, 0) for c in ("published", "researched", "list"))
    print(f"\nat confidence >= {TIERS['list']}: {sendable} contacts")
    print(f"below that, needing re-resolution: {total - sendable}")

    if not args.apply:
        print("\ndry run, nothing written. re-run with --apply")
        con.close()
        return 0

    con.executemany(
        f"UPDATE contacts SET email_confidence = ?, email_provenance = ?,"
        f" confidence_scored_at = '{now}' WHERE id = ?",
        updates,
    )
    con.commit()
    print(f"\nwrote {con.total_changes} rows")
    con.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
